# Faz o data.sql carregar DEPOIS que o Hibernate criar as tabelas
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Console do H2 pra você conferir os dados visualmente no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:barbearia
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

jwt.secret=minhaChaveSecretaSuperLongaParaAssinarTokensJWTComSeguranca123456
jwt.expiration=86400000